spring:
  profiles:
    active: test
---
spring:
  profiles: dev
  jpa:
    show-sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: toor
---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE